# Generated by Django 6.0.4 on 2026-05-01 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rol',
            field=models.CharField(blank=True, choices=[('paciente', 'Paciente'), ('recepcionista', 'Recepcionista'), ('medico', 'Medico')], max_length=20, null=True),
        ),
    ]
